# Generated by Django 4.0.2 on 2022-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
